env:
    node: true
    es2021: true
extends: eslint:recommended
parserOptions:
    ecmaVersion: latest
    sourceType: module
rules:
    indent:
        - 0
        - tab
    linebreak-style:
        - error
        - unix
    semi:
        - error
        - always
